config/routes.rb
Rails.application.routes.draw do
  resources :car_parts

  namespace :seller do
    resources :car_parts
  end
  namespace :admin do
    resources :car_parts
    resources :sellers
    resources :customers
  end

  devise_for :customers
  devise_for :sellers, controllers: {
    registrations: "devise_seller/registrations"
  }
  devise_for :admins, controllers: {
    registrations: "devise_admin/registrations"
  }

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end
  authenticated :seller_user do
    root to: "seller#index", as: :seller_root
  end

  root "home#index"

  get "admin", to: "admin#index"
  get "seller", to: "seller#index"
  get "home", to: "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_brand.rb
class CarBrand < ApplicationRecord
  has_many :car_brands
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :car_brand
  has_many :car_part
end

app/models/car_part.rb
class CarPart < ApplicationRecord
  belongs_to :car_model
  belongs_to :seller
  belongs_to :part_type
  validates :quantity, numericality: { greater_than_or_equal_to: 0, message: "quantity must be zero or greater" }
  validates :price, numericality: { greater_than_or_equal_to: 0, message: "price must be zero or greater" }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/part_type.rb
class PartType < ApplicationRecord
  has_many :car_part
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :car_parts
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/car_part_controller.rb
class CarPartController < ApplicationController
  def index
    @car_parts = CarPart.all
  end

  def show
    @car_part = CarPart.find(params[:id])
  end
end

app/controllers/car_parts_controller.rb
class CarPartsController < ApplicationController
  def index
    @car_parts = CarPart.all
  end

  def show
    @car_part = CarPart.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if admin_signed_in?
      redirect_to admin_path
    elsif seller_signed_in?
      redirect_to seller_path
    end
  end
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  before_action :authenticate_seller!

  def index
  end
end

app/helpers/admin/car_parts_helper.rb
module Admin::CarPartsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/sellers_helper.rb
module Admin::SellersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_parts_helper.rb
module CarPartsHelper
end

app/helpers/seller/car_parts_helper.rb
module Seller::CarPartsHelper
end

app/views/admin/index.html.erb
<h1>Admin Home</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris gravida massa quis ultricies scelerisque. Donec luctus ipsum eget quam tempus, nec blandit neque consectetur. Etiam ultrices velit eget enim viverra efficitur. Fusce mollis, lorem nec ornare pulvinar, sapien dolor semper massa, sit amet gravida nulla tellus volutpat dolor. Mauris iaculis ligula a finibus ullamcorper. Aenean sit amet nulla velit. Aliquam ut purus tempor, tempor felis sed, tempor ipsum.</p>
<p>Donec mattis mattis porttitor. Ut auctor ultricies massa, ut commodo ipsum feugiat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas interdum, ex ac luctus varius, tellus augue suscipit metus, eu finibus metus turpis sed quam. Suspendisse ac eros in ex tristique iaculis quis eget lacus. Nunc et nibh ipsum. Pellentesque lacinia dui eget blandit ullamcorper. Nam in ex lacinia, pellentesque neque non, vehicula augue. Fusce semper elementum lacus vitae euismod. Sed placerat velit eu tortor faucibus fringilla. Aliquam auctor, nisi vel ultrices blandit, nunc arcu dapibus eros, quis lacinia ligula dui a est. In quis lacinia eros.</p>

app/views/layouts/shared/_flash_messages.html.erb
<div class="m-2">
  <% if notice %>
    <div class="alert alert-success">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
</div>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-secondary">
  <div class="container-fluid">
    <%= link_to "Auto Part", root_path, class: "navbar-brand" %>
    <div class="me-auto">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Car Parts", car_parts_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div>
      <%= render "layouts/shared/users" %>
    </div>
  </div>
</nav>

app/views/layouts/shared/_users.html.erb
<div class="d-flex">
  <% if customer_signed_in? %>
    <div class="d-flex">
      <p class="mx-1 my-auto">
        <strong>Customer</strong>
        <%= link_to current_customer.email, edit_customer_registration_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
      </p>
      <%= link_to "Sign out", destroy_customer_session_path, class: "btn btn-primary mx-1", method: :delete, data: {turbo_method: :delete} %>
    </div>
  <% elsif !admin_signed_in? && !seller_signed_in? %>
    <div class="d-flex">
      <%= link_to "For seller", seller_path, class: "mx-1 my-auto link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
      <%= link_to "Sign up", new_customer_registration_path, class: "btn btn-primary mx-1" %>
      <%= link_to "Sign in", new_customer_session_path, class: "btn btn-primary mx-1" %>
    </div>
  <% end %>
</div>

app/views/layouts/shared/admin/_navbar.html.erb
<nav>
  <h4>Admin Dashboard</h4>
  <ul class="nav flex-column">
    <li class="nav-item"><%= link_to "admin path", admin_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Customers", admin_customers_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Sellers", admin_sellers_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Car parts", admin_car_parts_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Sign out", destroy_admin_session_path, class: "btn btn-primary mx-1", method: :delete, data: {turbo_method: :delete} %></li>
  </ul>
</nav>