config/routes.rb
Rails.application.routes.draw do
  resources :car_parts

  namespace :seller do
    resources :car_parts
  end
  namespace :admin do
    resources :car_parts
    resources :sellers
    resources :customers
  end

  devise_for :customers
  devise_for :sellers, controllers: {
    registrations: "devise_seller/registrations"
  }
  devise_for :admins, controllers: {
    registrations: "devise_admin/registrations"
  }

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end
  authenticated :seller_user do
    root to: "seller#index", as: :seller_root
  end

  root "home#index"

  get "admin", to: "admin#index"
  get "seller", to: "seller#index"
  get "home", to: "home#index"
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :car_parts
end

app/controllers/admin/sellers_controller.rb
class Admin::SellersController < AdminController
  before_action :set_seller, only: [ :show, :destroy ]

  def index
    @sellers = Seller.all
  end

  def show
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(seller_params)

    if @seller.save
      flash[:notice] = "Seller was seccessfully created"
    else
      flash[:alert] = "Failed to create seller"
    end

    redirect_to admin_sellers_path
  end

  def destroy
    if @seller.destroy
      flash[:notice] = "Car seller was seccessfully deleted"
    else
      flash[:alert] = "Failed to delete seller"
    end

    redirect_to admin_sellers_path
  end

  private
    def set_seller
      @seller = Seller.find(params[:id])
    end

    def seller_params
      params.require(:seller).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/seller/car_parts_controller.rb
class Seller::CarPartsController < SellerController
  before_action :set_car_part, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_seller!, only: [ :show, :edit, :update, :destroy ]

  def index
    @car_parts = CarPart.where(seller: current_seller)
  end

  def show
  end

  def new
    @car_part = CarPart.new
  end

  def edit
  end

  def create
    @car_part = current_seller.car_parts.new(car_part_params)

    if @car_part.save
      flash[:notice] = "Car part was seccessfully created"
    else
      flash[:alert] = "Failed to create car part"
    end

    redirect_to seller_car_parts_path
  end

  def update
    if @car_part.update(car_part_params)
      flash[:notice] = "Car part was seccessfully updated"
      render :show
    else
      flash[:alert] = "Failed to updated car part"
      render :edit
    end
  end

  def destroy
    if @car_part.destroy
      flash[:notice] = "Car part was seccessfully deleted"
    else
      flash[:alert] = "Failed to delete car part"
    end

    redirect_to seller_car_parts_path
  end

  private

    def authorize_seller!
      unless @car_part.seller == current_seller
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to seller_car_parts_path
      end
    end

    def set_car_part
      @car_part = CarPart.find(params[:id])
    end

    def car_part_params
      params.require(:car_part).permit(:name, :description, :price, :quantity, :car_model_id, :part_type_id)
    end
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  before_action :authenticate_seller!

  def index
  end
end

app/helpers/admin/sellers_helper.rb
module Admin::SellersHelper
end

app/helpers/seller/car_parts_helper.rb
module Seller::CarPartsHelper
end

app/views/admin/sellers/_form.html.erb
<%= form_with(model: [:admin, seller]) do |form| %>
  <% if seller.errors.any? %>
    <div>
      <h2><%= pluralize(seller.errors.count, "error") %></h2>
      <ul>
        <% seller.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="field">
      <%= form.label :email, class: "form-label" %><br />
      <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :password, class: "form-label" %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= form.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation, class: "form-label" %><br />
      <%= form.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>
  </div>
  <div>
    <%= form.submit "Create", class: "btn btn-primary my-2" %>
  </div>
<% end %>

app/views/admin/sellers/index.html.erb
<h1>Manage All Sellers</h1>
<%= link_to "Create seller", new_admin_seller_path, class: "btn btn-primary" %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Created</th>
      <th>Updated</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.id %></td>
        <td><%= seller.email %></td>
        <td><%= seller.created_at %></td>
        <td><%= seller.updated_at %></td>
        <td><%= link_to "more", admin_seller_path(seller), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/sellers/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <%= link_to "back", admin_sellers_path %>
    <h1>Seller new</h1>
    <%= render "form", seller: @seller %>
  </div>
</div>

app/views/admin/sellers/show.html.erb
<div>
  <%= link_to "back", admin_sellers_path %>
  <h1>Show seller</h1>
  <div>
    <p><strong>ID:</strong> <%= @seller.id %></p>
    <p><strong>Email:</strong> <%= @seller.email %></p>
    <p><strong>Created at:</strong> <%= @seller.created_at %></p>
    <p><strong>Updated at:</strong> <%= @seller.updated_at %></p>
  </div>
  <%= button_to "Delete", admin_seller_path(@seller), class: "btn btn-danger", method: :delete, data: {turbo_confirm: "Are you sure?"} %>
</div>