config/routes.rb
Rails.application.routes.draw do
  resources :car_parts

  namespace :seller do
    resources :car_parts
  end
  namespace :admin do
    resources :car_parts
    resources :sellers
    resources :customers
  end

  devise_for :customers
  devise_for :sellers, controllers: {
    registrations: "devise_seller/registrations"
  }
  devise_for :admins, controllers: {
    registrations: "devise_admin/registrations"
  }

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end
  authenticated :seller_user do
    root to: "seller#index", as: :seller_root
  end

  root "home#index"

  get "admin", to: "admin#index"
  get "seller", to: "seller#index"
  get "home", to: "home#index"
end

app/models/car_part.rb
class CarPart < ApplicationRecord
  belongs_to :car_model
  belongs_to :seller
  belongs_to :part_type
  validates :quantity, numericality: { greater_than_or_equal_to: 0, message: "quantity must be zero or greater" }
  validates :price, numericality: { greater_than_or_equal_to: 0, message: "price must be zero or greater" }
end

app/controllers/admin/car_parts_controller.rb
class Admin::CarPartsController < AdminController
  before_action :set_car_part, only: [ :show, :destroy ]

  def index
    @car_parts = CarPart.all
  end

  def show
  end

  def destroy
    if @car_part.destroy
      flash[:notice] = "Car part was seccessfully deleted"
    else
      flash[:alert] = "Failed to delete car part"
    end

    redirect_to admin_car_parts_path
  end

  private
    def set_car_part
      @car_part = CarPart.find(params[:id])
    end
end

app/controllers/car_part_controller.rb
class CarPartController < ApplicationController
  def index
    @car_parts = CarPart.all
  end

  def show
    @car_part = CarPart.find(params[:id])
  end
end

app/controllers/car_parts_controller.rb
class CarPartsController < ApplicationController
  def index
    @car_parts = CarPart.all
  end

  def show
    @car_part = CarPart.find(params[:id])
  end
end

app/controllers/seller/car_parts_controller.rb
class Seller::CarPartsController < SellerController
  before_action :set_car_part, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_seller!, only: [ :show, :edit, :update, :destroy ]

  def index
    @car_parts = CarPart.where(seller: current_seller)
  end

  def show
  end

  def new
    @car_part = CarPart.new
  end

  def edit
  end

  def create
    @car_part = current_seller.car_parts.new(car_part_params)

    if @car_part.save
      flash[:notice] = "Car part was seccessfully created"
    else
      flash[:alert] = "Failed to create car part"
    end

    redirect_to seller_car_parts_path
  end

  def update
    if @car_part.update(car_part_params)
      flash[:notice] = "Car part was seccessfully updated"
      render :show
    else
      flash[:alert] = "Failed to updated car part"
      render :edit
    end
  end

  def destroy
    if @car_part.destroy
      flash[:notice] = "Car part was seccessfully deleted"
    else
      flash[:alert] = "Failed to delete car part"
    end

    redirect_to seller_car_parts_path
  end

  private

    def authorize_seller!
      unless @car_part.seller == current_seller
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to seller_car_parts_path
      end
    end

    def set_car_part
      @car_part = CarPart.find(params[:id])
    end

    def car_part_params
      params.require(:car_part).permit(:name, :description, :price, :quantity, :car_model_id, :part_type_id)
    end
end

app/helpers/admin/car_parts_helper.rb
module Admin::CarPartsHelper
end

app/helpers/car_parts_helper.rb
module CarPartsHelper
end

app/helpers/seller/car_parts_helper.rb
module Seller::CarPartsHelper
end

app/views/admin/car_parts/index.html.erb
<h1>Manage All Car Parts</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Part Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Created</th>
      <th>Updated</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @car_parts.each do |car_part| %>
      <tr>
        <td><%= car_part.id %></td>
        <td><%= car_part.name %></td>
        <td><%= car_part.price %> €</td>
        <td><%= car_part.quantity %></td>
        <td><%= car_part.created_at %></td>
        <td><%= car_part.updated_at %></td>
        <td><%= link_to "more", admin_car_part_path(car_part), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/car_parts/show.html.erb
<div>
  <%= link_to "back", admin_car_parts_path %>
  <h1>Show car part</h1>
  <div>
    <p><strong>ID:</strong> <%= @car_part.id %></p>
    <p><strong>Name:</strong> <%= @car_part.name %></p>
    <p><strong>Price:</strong> <%= @car_part.price %> €</p>
    <p><strong>Quantity:</strong> <%= @car_part.quantity %></p>
    <p><strong>Part Type:</strong> <%= @car_part.part_type.name %></p>
    <p><strong>Car Model:</strong> <%= @car_part.car_model.name %></p>
    <p><strong>Car Brand:</strong> <%= @car_part.car_model.car_brand.name %></p>
    <p><strong>Description:</strong> <%= @car_part.description %></p>
    <p><strong>Created at:</strong> <%= @car_part.created_at %></p>
    <p><strong>Updated at:</strong> <%= @car_part.updated_at %></p>
  </div>
  <%= button_to "Delete", admin_car_part_path(@car_part), class: "btn btn-danger", method: :delete, data: {turbo_confirm: "Are you sure?"} %>
</div>